version: '2'
services:
  pihole:
    container_name: pihole
    image: diginc/pi-hole
    restart: always
    environment:
     - TZ=America/New_York
     - ServerIP=192.168.1.2
     - WEBPASSWORD=
    network_mode: host
    volumes:
      - /media/sp0gg/BIGGUN MKII/server_configs/pihole:/etc/pihole/
      - /media/sp0gg/BIGGUN MKII/server_configs/pihole/dnsmasq.d:/etc/dnsmasq.d/
    ports:
     - "53:53/tcp"
     - "53:53/udp"
     - "80:80"
