version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
#    user: "1026"
    environment:
      - TZ=America/New_York
    network_mode: host
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /volume2/server_configs/plex:/config
      - /volume2/transcode/:/transcode
      - /volume2/media/TV:/data/tv
      - /volume2/media/Movies:/data/movies
      - /volume2/media/Exercise:/data/exercise
      - /volume2/media/YouTube:/data/youtube
      - /volume2/media/Other:/data/other
      - /volume2/media/Music/:/data/music
  qbittorrent:
    container_name: qbittorrent
#    image: wernight/qbittorrent:3.3
#    image: linuxserver/qbittorrent
    image: linuxserver/qbittorrent:14.3.2.99202101080148-7233-0cbd15890ubuntu18.04.1-ls109
    restart: always
#    user: "1026:100"
    environment:
      - WEBUI_PORT=8080
      - TZ=America/New_York
      - PUID=1026
      - PGID=100
    ports:
      - "8080:8080"
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "20988:20988/tcp"
      - "20988:20988/udp"
    volumes:
      - /volume2/server_configs/qbittorrent:/config
      - /volume2/media/Downloads:/torrents
      - /volume2/media/Downloads:/downloads
      - /volume2/media/Downloads/blackhole:/blackhole
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
     - PUID=1026
     - PGID=100
     - TZ=America/New_York
    volumes:
     - /volume2/server_configs/sabnzbd:/config
     - /volume2/media/Downloads:/downloads
     - /volume2/media/Downloads/temp:/incomplete-downloads #optional
    ports:
       - 8880:8080
       - 9090:9090
    restart: always
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: always
#    user: "1026"
    environment:
      - TZ=America/New_York
      - PGID=100
      - PUID=1026
    ports:
      - "8989:8989"
    volumes:
      - /volume2/server_configs/sonarr:/config
      - /volume2/media/Downloads:/downloads
      - /volume2/media/TV:/tv
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: always
#    user: "1026"
    environment:
      - TZ=America/New_York
      - PGID=100
      - PUID=1026
    ports:
      - "7878:7878"
    volumes:
      - /volume2/server_configs/radarr:/config
      - /volume2/media/Downloads:/downloads
      - /volume2/media/Movies:/movies
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:latest
    environment:
      - TZ=America/New_York
      - PGID=100
      - PUID=1026
    volumes:
      - /volume2/server_configs/tautulli:/config
    ports:
      - 8181:8181
    restart: always
  iperf3:
    container_name: iperf3
    image: mlabbe/iperf3
    restart: always
    ports:
      - "5201:5201/tcp"
      - "5201:5201/udp"
#  lidarr:
#    container_name: lidarr
#    image: linuxserver/lidarr
#    restart: always
#    environment:
#      - TZ=America/New_York
#      - PGID=1000
#      - PUID=1000
#    ports:
#      - "8686:8686"
#    volumes:
#      - /volume2/server_configs/lidarr:/config
#      - /volume2/media/Downloads:/downloads
#      - /volume2/media/Music:/music
#  headphones:
#    container_name: headphones
#    image: linuxserver/headphones
#    restart: always
#    environment:
#      - TZ=America/New_York
#      - PGID=1000
#      - PUID=1000
#    ports:
#      - "8181:8181"
#    volumes:
#      - /volume2/server_configs/headphones:/config
#      - /volume2/media/Downloads:/downloads
#      - /volume2/media/Music:/music
#      - /volume2/media/Movies:/movies


